version: "3"
services:
  fhir-owl-server:
    # build: .
    image: jiaola/fhir-owl-server
    container_name: fhir-owl-server
    restart: on-failure
    ports:
      - "8090:8080"
    depends_on:
      - fhir-owl-graphdb
    links:
      - fhir-owl-graphdb
    env_file:
      - fhir-owl-server/.env
  fhir-owl-graphdb:
    image: ontotext/graphdb:8.11.0-free
    container_name: fun-owl-graphdb
    restart: always
    env_file:
      - graphdb/.env
    volumes:
      - fun-owl-graphdb:/opt/graphdb/home/data
    ports:
      - "7300:7200"
volumes:
  fun-owl-graphdb: